/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class Library {
    public boolean someLibraryMethod() {
        MathStuff stuff=new MathStuff(true,1,1);
        if(sign){
            stuff.calcValue();
        }
       System.out.println(sign);
       System.out.println(mantissa);
       System.out.println(exponent);
        return true;
    }
    private boolean sign;
    private double mantissa;
    private int exponent;
}
